# Generated by Django 3.2.10 on 2022-03-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOT',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(default=None, max_length=255)),
                ('device_voltage', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('device_kw', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('hours', models.PositiveIntegerField()),
            ],
        ),
    ]
