# Generated by Django 3.2.10 on 2022-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot',
            name='device_current',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, max_length=5),
            preserve_default=False,
        ),
    ]
