# Generated by Django 3.2.10 on 2022-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_iot_device_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iot',
            name='device_current',
        ),
    ]
