# Generated by Django 3.2.10 on 2022-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_iot_device_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot',
            name='device_current',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, max_length=5),
            preserve_default=False,
        ),
    ]
